{
  "0 debug pnpm:scope": {
    "selected": 1
  },
  "1 info pnpm": {
    "err": {
      "name": "Error",
      "message": "not found: new",
      "code": "ENOENT",
      "stack": "Error: not found: new\n    at getNotFoundError (/Users/patrick/.nvm/versions/node/v16.13.1/lib/node_modules/pnpm/dist/pnpm.cjs:41518:51)\n    at Function.whichSync [as sync] (/Users/patrick/.nvm/versions/node/v16.13.1/lib/node_modules/pnpm/dist/pnpm.cjs:41595:13)\n    at getCommandAbsolutePathSync (/Users/patrick/.nvm/versions/node/v16.13.1/lib/node_modules/pnpm/dist/pnpm.cjs:43160:44)\n    at default_1 (/Users/patrick/.nvm/versions/node/v16.13.1/lib/node_modules/pnpm/dist/pnpm.cjs:43169:32)\n    at /Users/patrick/.nvm/versions/node/v16.13.1/lib/node_modules/pnpm/dist/pnpm.cjs:171190:39"
    }
  },
  "2 error pnpm": {
    "code": "ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL",
    "prefix": "/Users/patrick/workspace/personal/qdriven/fluentqa-pydaily",
    "err": {
      "name": "pnpm",
      "message": "not found: new",
      "code": "ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL",
      "stack": "Error: not found: new\n    at getNotFoundError (/Users/patrick/.nvm/versions/node/v16.13.1/lib/node_modules/pnpm/dist/pnpm.cjs:41518:51)\n    at Function.whichSync [as sync] (/Users/patrick/.nvm/versions/node/v16.13.1/lib/node_modules/pnpm/dist/pnpm.cjs:41595:13)\n    at getCommandAbsolutePathSync (/Users/patrick/.nvm/versions/node/v16.13.1/lib/node_modules/pnpm/dist/pnpm.cjs:43160:44)\n    at default_1 (/Users/patrick/.nvm/versions/node/v16.13.1/lib/node_modules/pnpm/dist/pnpm.cjs:43169:32)\n    at /Users/patrick/.nvm/versions/node/v16.13.1/lib/node_modules/pnpm/dist/pnpm.cjs:171190:39"
    }
  }
}